name: PHP CI/CD Pipeline

on:
  push:
    branches:
      - Backend-PHP

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Deploy Application
      run: |
        # Define variables
        WEB_SERVER_DIR=C:\Users\nipun\webserver

        # Remove all files from the web server directory
        rm -rf $WEB_SERVER_DIR/*

        # Copy files to the web server directory
        cp -r * $WEB_SERVER_DIR

        # Optionally, start PHP's built-in web server
        php -S localhost:8000 -t $WEB_SERVER_DIR &
