name: PHP Workflow

on:
  push:
    branches: [ Backend-PHP ]
  pull_request:
    branches: [ Backend-PHP ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run Tests
      run: vendor/bin/phpunit
